export interface PluginItem {
  id: string;
  code: string;
  name: string;
}

export interface PluginEvaluation extends PluginItem {
  relevance: number;
  adherence: number;
  adherenceNote: string;
  notContracted: boolean;
  companySelections?: number[];
}

export const PLUGINS_WITH_COMPANY_QUESTION: { code: string; question: string }[] = [
  { code: "3.1", question: "Qual das empresas irá gerar faturamento?" },
  { code: "3.3", question: "Qual das empresas irá gerar faturamento?" },
  { code: "3.12", question: "Qual das empresas irá gerar faturamento?" },
  { code: "4.1.34", question: "Quais das empresas irão fazer movimentação de nota fiscal?" },
  { code: "4.1.14", question: "Quais as empresas que realizarão expedição pelo SIGEP?" },
];

export const PLUGIN_LIST: PluginItem[] = [
  { id: "p-1", code: "3.4", name: "Extranet" },
  { id: "p-2", code: "3.6", name: "EIS" },
  { id: "p-3", code: "3.7", name: "Revenda" },
  { id: "p-4", code: "3.9", name: "B2B - Licitação" },
  { id: "p-5", code: "3.15", name: "B2B - Portal" },
  { id: "p-6", code: "3.11", name: "M-Commerce / Catálogo de Produtos B2B" },
  { id: "p-7", code: "5.2.1", name: "PDV UNO (Online)" },
  { id: "p-8", code: "3.1", name: "NF-e Federal" },
  { id: "p-9", code: "3.3", name: "NFS-e / RPS" },
  { id: "p-10", code: "3.12", name: "NFC-e" },
  { id: "p-11", code: "3.16", name: "DANFE Simplificado" },
  { id: "p-12", code: "3.10", name: "NF-e Federal - NFCom Modelo 21 e 22" },
  { id: "p-13", code: "3.8.1", name: "Força de Vendas: Online" },
  { id: "p-14", code: "3.8.2", name: "Força de Vendas: Plug-in Off-line" },
  { id: "p-15", code: "4.1.69", name: "CRM" },
  { id: "p-16", code: "4.1.72", name: "OS – Ordem de Serviço" },
  { id: "p-17", code: "4.1.59", name: "Automação de entrega" },
  { id: "p-18", code: "4.1.64", name: "Separação / Picking" },
  { id: "p-19", code: "4.1.73", name: "Abastecimento Aeronave" },
  { id: "p-20", code: "4.1.75", name: "Inventario + Transferência de Estoque" },
  { id: "p-21", code: "4.1.80", name: "OC - Ocorrência" },
  { id: "p-22", code: "4.1.66", name: "APP Uno Mobile: Conferência Recebimento" },
  { id: "p-23", code: "4.1.82", name: "APP Uno Mobile: OP - Ordem de Produção" },
  { id: "p-24", code: "4.1.30/31/32", name: "Importação de Banco de Dados" },
  { id: "p-25", code: "4.1.1", name: "Homologação Boleto CNAB (Cobrança)" },
  { id: "p-26", code: "4.1.0", name: "Homologação Boleto API (Cobrança)" },
  { id: "p-27", code: "4.1.65", name: "DDA Banco Itaú" },
  { id: "p-28", code: "4.1.2", name: "Pagamento Escritural" },
  { id: "p-29", code: "4.1.47", name: "Integração / Registro da GNRE no Portal Nacional" },
  { id: "p-30", code: "4.1.34", name: "Radar de Monitoramento e Download de NFes e CTes" },
  { id: "p-31", code: "4.1.28", name: "E-mail NF e Boletos Unificados" },
  { id: "p-32", code: "4.1.18", name: "Conciliação Bancária OFX" },
  { id: "p-33", code: "4.1.24", name: "Gestão de Cartão de Crédito" },
  { id: "p-34", code: "4.1.79", name: "Windows AD" },
  { id: "p-35", code: "4.1.44", name: "Migração Plano de Contas" },
  { id: "p-36", code: "4.1.26", name: "Centralização Contas A RECEBER Multiempresa" },
  { id: "p-37", code: "4.1.27", name: "Centralização Contas A PAGAR Multiempresa" },
  { id: "p-38", code: "4.1.39", name: "EDI - Importação Arquivos" },
  { id: "p-39", code: "4.1.40", name: "EDI - Importação Contas a Pagar e Receber" },
  { id: "p-40", code: "4.1.50", name: "EDI - Transportadora + Auditoria de Frete" },
  { id: "p-41", code: "4.1.13", name: "Geração Propostas/Contratos em WORD" },
  { id: "p-42", code: "4.1.20", name: "SMS Coorporativo" },
  { id: "p-43", code: "4.1.22", name: "RD Station" },
  { id: "p-44", code: "4.1.77", name: "Field Control" },
  { id: "p-45", code: "4.1.53", name: "Peoplenect" },
  { id: "p-46", code: "4.1.6", name: "Configurador de Produto" },
  { id: "p-47", code: "4.1.7", name: "eProcurement" },
  { id: "p-48", code: "4.1.8", name: "Fórmulas de custo e rentabilidade" },
  { id: "p-49", code: "4.1.29", name: "Unidade de Medida Alternativa para Vendas e Recebimento" },
  { id: "p-50", code: "4.1.21", name: "Gráfico de Gantt + Painel de Projetos e Categoria" },
  { id: "p-51", code: "4.1.11", name: "CEF – SIATE (Sistema de Atendimento GSC – SIGSC)" },
  { id: "p-52", code: "4.1.19", name: "Fechamento HH (Hora x Homem)" },
  { id: "p-53", code: "4.1.12", name: "SPED – Exportação Bloco H e K" },
  { id: "p-54", code: "4.1.45", name: "Systax - Parametrização de Regras Fiscais" },
  { id: "p-55", code: "4.1.9", name: "Unificação Estoques" },
  { id: "p-56", code: "4.1.10", name: "UA (Unidade de Armazenagem)" },
  { id: "p-57", code: "4.1.46", name: "Atualização Base de CEP e IBGE" },
  { id: "p-58", code: "4.1.14", name: "SIGEP - Gerenciador de Postagens dos Correios" },
  { id: "p-59", code: "4.1.55", name: "Tracking / Acompanhamento de Entrega Correios" },
  { id: "p-60", code: "4.1.33", name: "Mecânica de Frete (Vendas) + Correios" },
  { id: "p-61", code: "4.1.15", name: "BOMI" },
  { id: "p-62", code: "4.1.17", name: "GENEXIS" },
  { id: "p-63", code: "4.1.23", name: "Eximbiz" },
  { id: "p-64", code: "4.1.38", name: "SerraPark Log" },
  { id: "p-65", code: "4.1.49", name: "Jadlog" },
  { id: "p-66", code: "4.1.52", name: "Mandaê" },
  { id: "p-67", code: "4.1.56", name: "Grupo Enar | Apoio Logística" },
  { id: "p-68", code: "4.1.57", name: "Central do Frete" },
  { id: "p-69", code: "4.1.42", name: "Gestão de Manutenção Preventivas" },
  { id: "p-70", code: "4.1.48", name: "Gestão de Normas e Certificados de Qualidade" },
  { id: "p-71", code: "4.1.51", name: "FCI - Ficha de Controle de Importação" },
  { id: "p-72", code: "4.1.58", name: "MPS - Plano Mestre de Produção" },
  { id: "p-73", code: "4.1.60", name: "Importação XML DI" },
  { id: "p-74", code: "4.1.62", name: "Importar Pedidos de Compras Franqueados" },
  { id: "p-75", code: "4.9", name: "Painel de Projetos Total" },
  { id: "p-76", code: "4.1.81", name: "Intelipost" },
  { id: "p-77", code: "4.1.83", name: "Boleto Protegido - Boletos falsos" },
  { id: "p-78", code: "4.2.1", name: "Integração (Contimatic, Cuca, Domínio, Folhamatic, Mega, Nooven, Prosoft, Unico, SAGE)" },
  { id: "p-79", code: "4.6.1", name: "Magento - Bizcommerce" },
  { id: "p-80", code: "4.6.3", name: "Vtex" },
  { id: "p-81", code: "4.6.59", name: "Loja Integrada" },
  { id: "p-82", code: "4.6.4", name: "Tray" },
  { id: "p-83", code: "4.6.60", name: "WooCommerce" },
  { id: "p-84", code: "4.6.61", name: "Bis2Bis – Magento" },
  { id: "p-85", code: "4.6.62", name: "Mercos – Força de vendas e e‑commerce B2B" },
  { id: "p-86", code: "4.1.41", name: "Flexy" },
  { id: "p-87", code: "4.6.58", name: "Auryn" },
  { id: "p-88", code: "4.1.35", name: "Madeira Madeira" },
  { id: "p-89", code: "4.1.78", name: "Hubspot" },
  { id: "p-90", code: "4.1.58b", name: "Skyhub" },
  { id: "p-91", code: "4.1.52b", name: "Mercado Livre" },
  { id: "p-92", code: "4.1.63", name: "Anymarket" },
  { id: "p-93", code: "4.1.59b", name: "Ideris" },
  { id: "p-94", code: "4.6.63", name: "Nuvemshop" },
  { id: "p-95", code: "4.6.63b", name: "Bling" },
  { id: "p-96", code: "5.1", name: "PDV / ECF (Ponto de Venda / Emissor de Cupom Fiscal) (Em construção)" },
  { id: "p-97", code: "5.2", name: "SOMA LF (SPED)" },
  { id: "p-98", code: "5.5", name: "COMEX" },
  { id: "p-99", code: "9.1.12C", name: "Agente de Impressão UNO ERP" },
];

